site:
  title: TrustyAI
  start_page: trustyai-site::main.adoc
content:
  sources:
  - url: .
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle
output:
  clean: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: '@djencks/asciidoctor-mathjax'