site:
  title: TrustyAI
  url: https://trustyai.org
  start_page: docs::main.adoc
content:
  sources:
  - url: .
    start_path: docs
    branches: ['main', 0.8.0, 0.9.0, 0.10.0]
    worktrees: true
    version: 'main'
ui:
  bundle:
    url: ./ui-bundle
output:
  clean: true
urls:
  html_extension_style: drop
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
    - require: '@djencks/asciidoctor-mathjax'