apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: housing
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: xgboost
      runtime: mlserver-1.x
      storageUri: "https://github.com/trustyai/model-collection/raw/housing-data/housing-data/model.json"
