apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "explainer-test-lime"
spec:
  predictor: <1>
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: https://github.com/trustyai-explainability/model-collection/raw/bank-churn/model.joblib <2>
  explainer: <3>
    containers:
        - name: explainer
          image: quay.io/trustyai/trustyai-kserve-explainer:latest <4>
